name: plan

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: [ "stage", "main" ]
    paths-ignore: [ "docs/**" ]

concurrency:
  group: {% raw %}${{ github.head_ref || github.run_id }}{% endraw %}
  cancel-in-progress: true

jobs:          
  build-and-plan-stage:
    environment: stage
    runs-on: ubuntu-latest
    if: {% raw %}${{ github.event.pull_request.base.ref == 'stage' }}{% endraw %}
    steps:
      - name: build and plan stage
        uses: ./.github/actions/build-and-plan
        with:
          compose-config-args: "-f production.yml -f staging.yml"
          tf-api-token: {% raw %}${{ secrets.TF_API_TOKEN }}{% endraw %}
          ssh-key: {% raw %}${{ secrets.TF_API_TOKEN }}{% endraw %}
          droplet-host: {% raw %}${{ secrets.DROPLET_HOST }}{% endraw %}
          env: stage
          github-token: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}

  build-and-plan-prod:
    environment: prod
    runs-on: ubuntu-latest
    if: {% raw %}${{ github.event.pull_request.base.ref == 'main' }}{% endraw %}
    steps:
      - name: build and plan prod
        uses: ./.github/actions/build-and-plan
        with:
          compose-config-args: "-f production.yml"             
          tf-api-token: {% raw %}${{ secrets.TF_API_TOKEN }}{% endraw %}
          ssh-key: {% raw %}${{ secrets.TF_API_TOKEN }}{% endraw %}
          droplet-host: {% raw %}${{ secrets.DROPLET_HOST }}{% endraw %}
          env: prod
          github-token: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
