name: build and plan
description: Github Action to build (Docker) and plan (Terraform) changes.
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  compose-config-args:
    description: 'Docker compose config arguments. Example: "-f production.yml".'
    required: true
  tf-version:
    description: 'Terraform version. Example: "1.3.4".'
    required: false
    default: "1.3.4"
  tf-api-token:
    description: 'Terraform cloud API token.'
    required: true
  ssh-key:
    description: 'SSH key.'
    required: true
  droplet-host:
    description: 'Host of the droplet. Example: "172.16.254.1".'
    required: true
  env:
    description: 'Environment. Example: "prod".'
    required: true
  github-token:
    description: 'GitHub token.'
    required: true

runs:
  using: "composite"
  steps:
    - name: build the stack
      shell: bash
      run:  docker-compose {% raw %}${{ inputs.compose-config-args }}{% endraw %} up -d --build

    - name: tear down the stack
      shell: bash
      run:  docker-compose {% raw %}${{ inputs.compose-config-args }}{% endraw %} down

    - name: setup terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: {% raw %}${{ inputs.tf-version }}{% endraw %}
        cli_config_credentials_token: {% raw %}${{ inputs.tf-api-token }}{% endraw %}

    - name: install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: {% raw %}${{ inputs.ssh-key }}{% endraw %}
        name: id_rsa # optional
        known_hosts: unnecessary
        if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)

    - name: add known hosts
      shell: bash
      run: ssh-keyscan -H {% raw %}${{ inputs.droplet-host }}{% endraw %} >> ~/.ssh/known_hosts

    - name: initialize terraform
      shell: bash
      run: make init-{% raw %}${{ inputs.env }}{% endraw %} TF_FLAGS="-input=false"

    - name: plan terraform
      id: plan
      continue-on-error: true
      shell: bash
      run: make plan-{% raw %}${{ inputs.env }}{% endraw %}="-input=false -no-color"

    - name: post plan to github PR
      uses: mshick/add-pr-comment@v1
      with:
        allow-repeats: true
        repo-token: {% raw %}${{ inputs.github-token }}{% endraw %}
        repo-token-user-login: 'github-actions[bot]'
        message: |
          ```diff
          {% raw %}${{ steps.plan.outputs.stdout }}{% endraw %}
          ```

    - name: fail if plan fails
      if: steps.plan.outcome == 'failure'
      shell: bash
      run: exit 1
