name: deploy
description: Github Action to deploy build (Docker), apply (Terraform) and deploy (rsync+docker-compose) changes.
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  tf-version:
    description: 'Terraform version. Example: "1.3.4".'
    required: false
    default: "1.3.4"
  tf-api-token:
    description: 'Terraform cloud API token.'
    required: true
  ssh-key:
    description: 'SSH key.'
    required: true
  droplet-host:
    description: 'Host of the droplet. Example: "172.16.254.1".'
    required: true
  env:
    description: 'Environment. Example: "prod".'
    required: true
  github-token:
    description: 'GitHub token.'
    required: true
  droplet-user:
    description: 'User to run commands in the droplet. Example: "ubuntu".'
    required: true
  compose-config-args:
    description: 'Docker compose config arguments. Example: "-f production.yml".'
    required: true

runs:
  using: "composite"
  steps:
    - name: setup terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: {% raw %}${{ inputs.tf-version }}{% endraw %}
        cli_config_credentials_token: {% raw %}${{ inputs.tf-api-token }}{% endraw %}

    - name: install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: {% raw %}${{ inputs.ssh-key }}{% endraw %}
        name: id_rsa # optional
        known_hosts: unnecessary
        if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)

    - name: add known hosts
      shell: bash
      run: ssh-keyscan -H {% raw %}${{ inputs.droplet-host }}{% endraw %} >> ~/.ssh/known_hosts

    - name: initialize terraform
      shell: bash
      run: make init-{% raw %}${{ inputs.env }}{% endraw %} TF_FLAGS="-input=false"

    - name: plan terraform
      id: plan
      continue-on-error: true
      shell: bash
      run: make plan-{% raw %}${{ inputs.env }}{% endraw %} TF_FLAGS="-input=false -no-color"

    - name: apply terraform
      if: steps.plan.outcome == 'success'
      id: apply
      continue-on-error: true
      shell: bash
      run: make apply-{% raw %}${{ inputs.env }}{% endraw %} TF_FLAGS="-auto-approve -input=false -no-color"

    - name: post plan and apply to github PR
      if: steps.plan.outcome == 'success' && steps.apply.outcome == 'success'
      uses: mshick/add-pr-comment@v1
      with:
        repo-token: {% raw %}${{ inputs.github-token }}{% endraw %}
        repo-token-user-login: 'github-actions[bot]'
        message: |
          Applying **{% raw %}${{ inputs.env }}{% endraw %}**:
          ```diff
          {% raw %}${{ steps.plan.outputs.stdout }}{% endraw %}
          ```
          ```
          {% raw %}${{ steps.apply.outputs.stdout }}{% endraw %}
          ```

    - name: add plan failure to PR
      if: steps.plan.outcome == 'failure'
      uses: mshick/add-pr-comment@v1
      with:
        repo-token: {% raw %}${{ inputs.github-token }}{% endraw %}
        repo-token-user-login: 'github-actions[bot]'
        message: |
          Plan failed for **{% raw %}${{ inputs.env }}{% endraw %}**:
          ```
          {% raw %}${{ steps.plan.outputs.stderr }}{% endraw %}
          ```

    - name: fail if plan fails
      if: steps.plan.outcome == 'failure'
      shell: bash
      run: exit 1

    - name: add apply failure to PR
      if: steps.apply.outcome == 'failure'
      uses: mshick/add-pr-comment@v1
      with:
        repo-token: {% raw %}${{ inputs.github-token }}{% endraw %}
        repo-token-user-login: 'github-actions[bot]'
        message: |
          Apply failed for **{% raw %}${{ inputs.env }}{% endraw %}**:
          ```
          {% raw %}${{ steps.apply.outputs.stderr }}{% endraw %}
          ```

    - name: fail if apply fails
      if: steps.apply.outcome == 'failure'
      shell: bash
      run: exit 1

    - name: deploy with rsync
      shell: bash
      run: rsync -avz ./app {% raw %}${{ inputs.droplet-user }}{% endraw %}@{% raw %}${{ inputs.droplet-host }}{% endraw %}:~

    - name: docker compose up
      uses: appleboy/ssh-action@master
      with:
        host: {% raw %}${{ inputs.droplet-host }}{% endraw %}
        username: {% raw %}${{ inputs.droplet-user }}{% endraw %}
        key: {% raw %}${{ inputs.ssh-key }}{% endraw %}
        script: docker-compose {% raw %}${{ inputs.compose-config-args }}{% endraw %} up -d --build
